<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Class Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #1e3a8a; }
        .header p { margin: 5px 0; color: #666; font-size: 14px;}
        .table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f8fafc; color: #1e3a8a; font-weight: bold; }
        .table tr:nth-child(even) { background-color: #fcfcfc; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #aaa; }
        .rate-good { color: #10b981; }
        .rate-bad { color: #ef4444; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Attendance Report</h1>
        <p><strong>Class:</strong> {{ $classSection->subject->code ?? 'N/A' }} - {{ $classSection->name }}</p>
        <p><strong>Faculty:</strong> {{ $facultyName }} | <strong>Date:</strong> {{ $date }}</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Total</th>
                <th>Present</th>
                <th>Late</th>
                <th>Excused</th>
                <th>Absent</th>
                <th>Rate</th>
            </tr>
        </thead>
        <tbody>
            @foreach($studentStats as $stat)
                <tr>
                    <td>{{ $stat['id'] }}</td>
                    <td>{{ $stat['name'] }}</td>
                    <td style="text-align: center;">{{ $stat['total_sessions'] }}</td>
                    <td style="text-align: center;">{{ $stat['present'] }}</td>
                    <td style="text-align: center;">{{ $stat['late'] }}</td>
                    <td style="text-align: center;">{{ $stat['excused'] }}</td>
                    <td style="text-align: center;">{{ $stat['absences'] }}</td>
                    <td class="{{ (int)$stat['rate'] < 80 ? 'rate-bad' : 'rate-good' }}" style="text-align: center;">
                        <strong>{{ $stat['rate'] }}</strong>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Student Attendance System
    </div>
</body>
</html>
