<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Student Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #1e3a8a; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #1e3a8a; }
        .header p { margin: 5px 0; color: #666; font-size: 14px; }
        .section-title { color: #1e3a8a; font-size: 16px; margin-top: 20px; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f8fafc; color: #1e3a8a; font-weight: bold; }
        .table tr:nth-child(even) { background-color: #fcfcfc; }
        .footer { position: fixed; bottom: -20px; left: 0; right: 0; text-align: center; font-size: 10px; color: #aaa; }
        .rate-good { color: #10b981; }
        .rate-bad { color: #ef4444; }
        .badge { display: inline-block; padding: 3px 6px; border-radius: 4px; font-size: 10px; font-weight: bold; color: white;}
        .bg-present { background-color: #10b981; }
        .bg-absent { background-color: #ef4444; }
        .bg-late { background-color: #f59e0b; }
        .bg-excused { background-color: #6b7280; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Personal Attendance Report</h1>
        <p><strong>Student:</strong> {{ $student->first_name }} {{ $student->last_name }} ({{ $student->identity_id }})</p>
        <p><strong>Semester:</strong> {{ $semester }} | <strong>Date:</strong> {{ $date }}</p>
    </div>

    <h2 class="section-title">Subject Breakdown</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Subject</th>
                <th>Section</th>
                <th>Total</th>
                <th>Present</th>
                <th>Late</th>
                <th>Excused</th>
                <th>Absent</th>
                <th>Rate</th>
            </tr>
        </thead>
        <tbody>
            @forelse($subjectStats as $stat)
                <tr>
                    <td>{{ $stat['code'] }}</td>
                    <td>{{ $stat['section'] }}</td>
                    <td style="text-align: center;">{{ $stat['total'] }}</td>
                    <td style="text-align: center;">{{ $stat['present'] }}</td>
                    <td style="text-align: center;">{{ $stat['late'] }}</td>
                    <td style="text-align: center;">{{ $stat['excused'] }}</td>
                    <td style="text-align: center;">{{ $stat['absent'] }}</td>
                    <td class="{{ (int)$stat['rate'] < 80 ? 'rate-bad' : 'rate-good' }}" style="text-align: center;">
                        <strong>{{ $stat['rate'] }}</strong>
                    </td>
                </tr>
            @empty
                <tr><td colspan="8" style="text-align:center">No active subjects found.</td></tr>
            @endforelse
        </tbody>
    </table>

    <h2 class="section-title">Recent Records (Last 20)</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Subject</th>
                <th>Status</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @forelse($recentRecords as $record)
                <tr>
                    <td>{{ $record->session->date->format('M d, Y') }}</td>
                    <td>{{ $record->session->classSection->subject->code ?? 'N/A' }}</td>
                    <td>
                        @php
                            $bgClass = match($record->status) {
                                'present' => 'bg-present',
                                'absent' => 'bg-absent',
                                'late' => 'bg-late',
                                'excused' => 'bg-excused',
                                default => 'bg-excused'
                            };
                        @endphp
                        <span class="badge {{ $bgClass }}">{{ ucfirst($record->status) }}</span>
                    </td>
                    <td>{{ $record->remarks ?? '--' }}</td>
                </tr>
            @empty
                <tr><td colspan="4" style="text-align:center">No recent records.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by Student Attendance System
    </div>
</body>
</html>
