<p>Hello,</p>

<p>Please find attached the automated <strong>{{ $reportConfig->name }}</strong> report generated by the Student Attendance Management System.</p>

<p>This report was generated according to your scheduled preferences.</p>

<p>Thank you,<br>
System Administrator</p>
